import pasta from "@/static/product/productSugar.png"
import water from "@/static/product/productWater.png"


export const products = [
    {
        id: 1,
        title: "Макаронные изделия Макфа Триколлини свитки",
        imageUrl: pasta,
        discount:0,
        stars: 4,
        feedback:3254,
        price: 151,
        weight:450,
        slug: "pasta",
        favorite: true ,
    },{
        id: 2,
        title: "Макаронные изделия Макфа Триколлини свитки",
        imageUrl: pasta,
        discount: 26,
        stars: 4,
        feedback:3254,
        price: 120,
        weight:450,
        slug: "pasta",
        favorite: false ,
    },{
        id: 3,
        title: "Макаронные изделия Макфа Триколлини свитки",
        imageUrl: pasta,
        discount: 26,
        stars: 4,
        feedback:3254,
        price: 120,
        weight:450,
        slug: "pasta",
        favorite: false ,
    },{
        id: 4,
        title: "Макаронные изделия Макфа Триколлини свитки",
        imageUrl: pasta,
        discount: 26,
        stars: 4,
        feedback:3254,
        price: 120,
        weight:450,
        slug: "pasta",
        favorite: false ,
    },
    {
        id: 5,
        title: "Макаронные изделия Макфа Триколлини свитки",
        imageUrl: pasta,
        discount:0,
        stars: 4,
        feedback:3254,
        price: 151,
        weight:450,
        slug: "pasta",
        favorite: true ,
    },{
        id: 6,
        title: "Макаронные изделия Макфа Триколлини свитки",
        imageUrl: pasta,
        discount: 26,
        stars: 4,
        feedback:3254,
        price: 120,
        weight:450,
        slug: "pasta",
        favorite: false ,
    },{
        id: 7,
        title: "Макаронные изделия Макфа Триколлини свитки",
        imageUrl: pasta,
        discount: 26,
        stars: 4,
        feedback:3254,
        price: 120,
        weight:450,
        slug: "pasta",
        favorite: false ,
    },{
        id: 8,
        title: "Макаронные изделия Макфа Триколлини свитки",
        imageUrl: pasta,
        discount: 26,
        stars: 4,
        feedback:3254,
        price: 120,
        weight:450,
        slug: "pasta",
        favorite: false ,
    },
    {
        id: 9,
        title: "Макаронные изделия Макфа Триколлини свитки",
        imageUrl: pasta,
        discount:0,
        stars: 4,
        feedback:3254,
        price: 151,
        weight:450,
        slug: "pasta",
        favorite: true ,
    },{
        id: 10,
        title: "Макаронные изделия Макфа Триколлини свитки",
        imageUrl: pasta,
        discount: 26,
        stars: 4,
        feedback:3254,
        price: 120,
        weight:450,
        slug: "pasta",
        favorite: false ,
    },{
        id: 11,
        title: "Макаронные изделия Макфа Триколлини свитки",
        imageUrl: pasta,
        discount: 26,
        stars: 4,
        feedback:3254,
        price: 120,
        weight:450,
        slug: "pasta",
        favorite: false ,
    },{
        id: 12,
        title: "Макаронные изделия Макфа Триколлини свитки",
        imageUrl: pasta,
        discount: 26,
        stars: 4,
        feedback:3254,
        price: 120,
        weight:450,
        slug: "pasta",
        favorite: false ,
    },

]